version: '3'

services: 
 db:
  container_name: mongodb
  image: mongo:6
  restart: always
  ports:
    - "27017:27017"
  environment:
    - MONGO_INITDB_ROOT_USERNAME=userName
    - MONGO_INITDB_ROOT_PASSWORD=userPwd
    - MONGO_INITDB_DATABASE=admin
  volumes:
   - ./mongo:/data/db
  networks:
   - test-network

networks:
  test-network:
    driver: bridge